#!/usr/bin/env bash

# Script for running miniJava compiler tests. 
# (For CS321 Language and Compiler Design, Portland State University.)
#
# Usage:
#   ./run tst/test01.java  -- test a single program 
#   ./run tst/test*.java   -- test all programs
#
# The script will compare your parser's output with a ref file (if exists),
# and save the diffs in a .diff file.
#

for i
do
	d=`dirname $i`
	f=`basename $i .java`
	echo -n "$d/$f: "
	java Parser $d/$f.java 1> $d/$f.ast
        diff -w $d/$f.ast $d/$f.ast.ref > $d/$f.ast.diff; 
        if [ -s $d/$f.ast.diff ]; then 
          echo "differs from ref (see $f.ast.diff)"; 
        else
          echo "matches ref"; 
          rm $d/$f.ast.diff; 
        fi
done
exit 0

